### ISSUE TITLE
No requirements file at all?

### ISSUE THREAD

**Issue by eyildiz-ugoe** [henrypinkard/DeepAF#3]
I got the code downloaded but there is no requirements package along with it, meaning that we have to hit-and-try or try to guess what packages/libraries were used. I just found out my tensorflow wasn't compatible with this one after receiving tons of errors. 

Could the author provide the outcome of "pip freeze" command on his system? The outcome would be the necessary requirements.txt file basically. Doing this would save a lot of time for those who want to use/build upon this valuable work.

**Comment by henrypinkard** [comment]
This code is 6 years old and the environment used for it is long gone at this point. I believe it uses a very old tensorflow API as well. If you can't get it to work as is, best bet might be to try to remake the algorithm with more modern packages

**Comment by eyildiz-ugoe** [comment]
OK, thanks :)
